project.clj, src/promesa/core.cljs, test/promesa/core_tests.cljs
It's a bit strange to have to use `resolve` instead of `promise` to create a promise containing a function but it probably is the most expected behavior. Maybe we should add a note mentioning it to the docs?
=> Applicative

src/promesa/core.cljc, test/promesa/core_tests.cljc
Closes #9 
I used a multimethod for the `catch` test because I couldn't think of something simpler which is both applicable to an error and which doesn't compile to a Javascript `Function`.
I noticed that non Error objects can be passed to `reject` in Clojurescript, but not in Clojure - not sure whether you're interested in preserving that constraint across platforms, so I haven't created an issue.
=> Support non-Function promise callbacks in cljs

src/promesa/core.cljc, test/promesa/core_tests.cljc
On the JVM, the Object protocol extension catches Boolean/String, but not in Javascript.
P.S. How do you feel about extending to nil, or that'd have surprising consequences?  The non-nil requirement can make some `alet` bodies a little awkward.
=> Extend IPromiseFactory to cover boolean&string in cljs

src/promesa/core.cljc, test/promesa/core_tests.cljc
I upgraded to 1.1.0 and bumped into `TypeError: writer.write is not a function` in a cljs repl.  The test I added errors in master.
Thanks for all your work on the project.
=> Use IWriter.-write in js/Promise's IPrintWithWriter impl

assets/_bluebird/externs.js
This allows the tests to pass w/ `:optimizations` `:advanced`
=> Add Promise.noConflict to _bluebird/externs.js

test/promesa/core_tests.cljc
Fix `t/is` usage in 3 tests. 
plus spelling fix
=> Small fixes in tests

src/promesa/core.cljc
Fix for #32.  I tried testing this, but it looked like it might require CountDownLatch or similar within the test to ensure we give the finally function a fair chance to run in all cases.  I was going w/ something like:
```clojure
(t/deftest finally
(let [p          (p/resolved 1)
completed? (atom false)]
(p/finally p
(fn []
(reset! completed? true)))
#?(:cljs
(t/async done
(p/then p
(fn [_]
(t/is @completed?)
(done))))
:clj
(do
@p
(t/is @completed?)))))
```
But it was only passing intermittently, and didn't seem like it was worth making the test much more complicated.  Happy to separately add tests for finally, though.
=> In core/finally, ignore cb args & call supplied fn w/ no args

project.clj, src/promesa/core.cljc, test/promesa/core_tests.cljc, test/promesa/issue_36.cljs, test/promesa/test_helpers.cljc
Fix for https://github.com/funcool/promesa/issues/36.
The following code will now be able to run:
```
(ns catfacts.scratch
(:require [promesa.core :as p
:refer [await]
:rename {await <!}
:refer-macros [alet]]))
(def nodegit (js/require "nodegit"))
(def repo (.-Repository nodegit))
(-> (alet [r (<! (.open repo ".."))
commit (<! (.getBranchCommit r "master"))
message (<! (.message commit))]
(println message))
(p/catch  (fn [err]
(println "ERROR:" err))))
```
=> Allow renaming of await in alet macro

src/promesa/core.cljc, test/promesa/core_tests.cljc
Closes #35.
Note that I didn't touch bind, which I think is a candidate for removal, because it behaves identically to then in cljs, and the only difference in clj is that bind will throw an exception if the callback doesn't return a promise.
=> In clj, resolve promises returned by `then` callbacks

assets/_bluebird/externs.js, src/promesa/core.cljc, src/promesa/impl.cljc
When using Promise with advanced compilation for ClojureScript, you'll get error messages like this:
WARNING: /whatever/promesa/core.js:254: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return p.finally(callback);
^
```
WARNING: /whatever/promesa/impl/promise.js:41: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return it__$1.catch(((function (it__$1){
^
```
This patch makes the messages go away by using the aliases `.lastly` and `.caught` provided by Bluebird for backwards …
=> Avoid compiler warnings caused by .finally/.catch

src/promesa/core.cljc
It is often useful to apply functions from clojure.core to
promesa.core/all's result e.g.
```
(-> (p/all bunch-of-promises)
(p/then (fn [results]
(conj results :foo)))
(p/then something-else))
```
In the current cljs implementation, results is a javascript native
array. Which means the code above will fail. What I end up doing very
often is calling `vec` or `list` over `results`.
The intention of this PR is to convert the result of a `promesa.core/all` promise
to a clojure datastructure.
I also added more documentation.
=> Convert promesa.core/all's result to a vector

src/promesa/async.clj, src/promesa/impl.cljc, test/promesa/core_tests.cljc
This PR is to fix the error below when trying to compile promesa and/or other libraries that depend on it such as httpurr for GraalVM native image. Please let me know if this is a viable option, or if you'd like to work on alternative approaches.
A similar issue was resolved for `core.async` in [ASYNC-216](https://clojure.atlassian.net/browse/ASYNC-216) with the same approach and released on `0.4.490`.
```Detailed message:
Error: Detected the ForkJoinPool.commonPool() in the image heap. The common pool must be created at run time because the parallelism depends on the number of cores available at run time. Therefore the common pool used during image generation must not be reachable, e.g., via a static field that caches a copy of the common pool. The object was probably created by a class …
```
=> Delay creating default executor to support GraalVM native compilation

doc/content.adoc
Love your project.
I was reading the documentation and, if you don't mind, I have some suggestions to help it flow a little more smoothly. I tried avoid any significant changes in case I misunderstood something. So, the changes should mostly be small adjustments to grammar or punctuation, but there are a few rephrases.
I could offer more suggestions for the Execution Model section, but I wasn't confident in my reading. Part of it might be that I'm out of practice with JVM concurrency. I had the following questions as I was reading that section:
- In the default `promisea` execution model, do all promises execute in a single alternate thread, similar to a single `agent`?
- Do all promises share this thread or just that particular promise chain?
- Do they spin off a separate thread or share …
=> Improve documentation.

src/promesa/impl.cljc
Version `6.0.0` fixed a CLJS bug where non-promise objects couldn't have callbacks chained to them using `then`. This fix _wasn't_ applied to non-`CompletableFuture` objects in JVM-based Clojure, which results in the library having different semantics of `then` depending on the runtime, which can be confusing to library users.
Example of the bug in Clojure 1.10.1:
```Clojure
(in-ns 'promesa.core)
=> #object[clojure.lang.Namespace 0x4b8e160c "promesa.core"]
Loading src/promesa/core.cljc... done
(def v "hello")
=> #'promesa.core/v
(then v println)
Execution error (IllegalArgumentException) at promesa.protocols/eval1521$fn$G (protocols.cljc:28).
No implementation of method: :-then of protocol: #'promesa.protocols/IPromise found for class: java.lang.String
```
This MR fixes this discrepancy …
=> Properly handle nil/Object instances on `then`

src/promesa/exec.cljc
I just came across this issue where the constructor parameter is not correctly handled (at least my assumption is that the intended behavior is the proposed one 🙂 )
=> Fix scheduled-pool constructor

test/promesa/tests/core_test.cljc
Fix error found via clj-kondo:
Single operand use of cljs.core/= is always true
=> Remove extra parens in timeout-test-2

src/promesa/core.cljc
Hello, I notice I lacked the docstrings for the new macros when I was checking the cljdocs, this PR adds some description and examples to them.
=> Add docstrings to thread macros

src/promesa/core.cljc, test/promesa/tests/core_test.cljc
To complete the threading functionality from `clojure.core`, this adds support for an async `as->` variant.
=> Add support for async as-> thread macro.

src/promesa/core.cljc, test/promesa/tests/core_test.cljc
Works like `with-redefs` but accepts promises in the body and waits until they
finish before restoring their original var values
=> Added with-redefs macro and tests

.travis.yml, README.md
- Updates readme to surface how to run tests
- Updates .travis.yml to use `build` instead of `build:tests` which does not
seem to exist and was not referenced in tools.clj
=> Add testing instructions to readme and update ci

src/promesa/exec/csp/channel.cljc, test/promesa/tests/exec_csp_test.cljc
when a channel is `close!`d any transducer state should always be flushed by calling the completion arity
this PR ensures that happens
=> CSP: always call transducer completion arity
